#!/usr/bin/env python3
"""Stable public facade for deterministic Relution OpenAPI catalog rendering."""

from __future__ import annotations

from relution_openapi_catalog_render import render_catalog
from relution_openapi_cli import atomic_write, main, parse_args
from relution_openapi_contract import (
    FIXED_HTTP_METHOD_FIELDS,
    HTTP_TOKEN,
    OAS_32_FIXED_HTTP_METHOD_FIELDS,
    PATH_ITEM_METADATA_KEYS,
    SUPPORTED_OPENAPI_VERSION,
    Path,
    Sequence,
    additional_operation,
    additional_operations,
    callback_lineage,
    callback_override_items,
    collect_named_callback,
    collect_operation_callbacks,
    collect_operations,
    collect_path_item_operations,
    collect_surface_operations,
    contract_feature_version,
    fixed_http_method_fields,
    fixed_operations,
    load_spec,
    load_strict_json,
    operations_from_path_item,
    resolve_callback_object,
    resolve_local_ref,
    resolve_path_item,
    validate_contract_surface,
    validate_path_item_keys,
    validate_top_level_objects,
)
from relution_openapi_machine_builder import (
    build_machine_catalog,
    operation_machine_key,
    render_machine_catalog,
)
from relution_openapi_machine_data import (
    catalog_contract_servers,
    catalog_media_content,
    catalog_openapi_server,
    catalog_operation_servers,
    catalog_parameter,
    catalog_parameters,
    catalog_request_body,
    catalog_response_headers,
    catalog_responses,
    catalog_security,
    catalog_security_schemes,
)
from relution_openapi_machine_schema import (
    SCHEMA_BOOLEAN_FIELDS,
    SCHEMA_CONSTRAINT_FIELDS,
    SCHEMA_STRING_FIELDS,
    schema_catalog_additional_properties,
    schema_catalog_booleans,
    schema_catalog_children,
    schema_catalog_identity,
    schema_catalog_scalar_fields,
    schema_catalog_strings,
    schema_catalog_structure,
    schema_catalog_summary,
    schema_catalog_type,
)
from relution_openapi_markdown import (
    contract_servers,
    operation_parameters,
    operation_servers,
    render_parameters,
    render_request_body,
    render_responses,
    render_security_schemes,
    render_server,
    response_content_summary,
    security_schemes,
)
from relution_openapi_markdown_common import (
    code,
    compact_text,
    json,
    quote_block,
    schema_annotation_summary_parts,
    schema_boolean_annotations,
    schema_bound_annotations,
    schema_fallback_summary,
    schema_nested_summary_parts,
    schema_scalar_summary_parts,
    schema_summary,
    schema_type_summary_parts,
    schema_value_annotations,
    security_requirement_summary,
    security_scheme_summary,
    security_summary,
)
from relution_openapi_types import Any, Mapping, Operation, dataclass, re


SCRIPT_ROOT = Path(__file__).resolve().parent


__all__ = (
    "Any",
    "FIXED_HTTP_METHOD_FIELDS",
    "HTTP_TOKEN",
    "Mapping",
    "OAS_32_FIXED_HTTP_METHOD_FIELDS",
    "Operation",
    "PATH_ITEM_METADATA_KEYS",
    "Path",
    "SCHEMA_BOOLEAN_FIELDS",
    "SCHEMA_CONSTRAINT_FIELDS",
    "SCHEMA_STRING_FIELDS",
    "SCRIPT_ROOT",
    "SUPPORTED_OPENAPI_VERSION",
    "Sequence",
    "additional_operation",
    "additional_operations",
    "atomic_write",
    "annotations",
    "build_machine_catalog",
    "callback_lineage",
    "callback_override_items",
    "catalog_contract_servers",
    "catalog_media_content",
    "catalog_openapi_server",
    "catalog_operation_servers",
    "catalog_parameter",
    "catalog_parameters",
    "catalog_request_body",
    "catalog_response_headers",
    "catalog_responses",
    "catalog_security",
    "catalog_security_schemes",
    "code",
    "collect_named_callback",
    "collect_operation_callbacks",
    "collect_operations",
    "collect_path_item_operations",
    "collect_surface_operations",
    "compact_text",
    "contract_feature_version",
    "contract_servers",
    "dataclass",
    "fixed_http_method_fields",
    "fixed_operations",
    "json",
    "load_spec",
    "load_strict_json",
    "main",
    "operation_parameters",
    "operation_machine_key",
    "operation_servers",
    "operations_from_path_item",
    "parse_args",
    "quote_block",
    "re",
    "render_catalog",
    "render_machine_catalog",
    "render_parameters",
    "render_request_body",
    "render_responses",
    "render_security_schemes",
    "render_server",
    "resolve_callback_object",
    "resolve_local_ref",
    "resolve_path_item",
    "response_content_summary",
    "schema_annotation_summary_parts",
    "schema_boolean_annotations",
    "schema_bound_annotations",
    "schema_catalog_additional_properties",
    "schema_catalog_booleans",
    "schema_catalog_children",
    "schema_catalog_identity",
    "schema_catalog_scalar_fields",
    "schema_catalog_strings",
    "schema_catalog_structure",
    "schema_catalog_summary",
    "schema_catalog_type",
    "schema_fallback_summary",
    "schema_nested_summary_parts",
    "schema_scalar_summary_parts",
    "schema_summary",
    "schema_type_summary_parts",
    "schema_value_annotations",
    "security_requirement_summary",
    "security_scheme_summary",
    "security_schemes",
    "security_summary",
    "validate_contract_surface",
    "validate_path_item_keys",
    "validate_top_level_objects",
)


if __name__ == "__main__":
    raise SystemExit(main())
